#!/usr/bin/env python2.7

# quick sqrt script, multiple inputs, tried to be clever
# no shell built ins or preloaded binaries present
# so i made this, slapped it in /usr/local/bin and called it a day

from sys import argv
from math import sqrt

usage = """
Python Square Root script
Usage: pyrt <num> <num2> -<num3>
"""

if 1 == len( argv ):
    print usage

# skip the first item as it will be program's name
for arg in argv[ 1: ]:
    try:
        if arg[ 0 ] == '-':
            num = float( arg[ 1: ])
            print arg + ": " + str( sqrt( num )) + "i"
            continue
        elif arg[ 0 ] == '+':
            num = float( arg[ 1: ])
        else:
            num = float( arg )

        print arg + ": " + str( sqrt( num ))
    except ValueError:
        print "'" + arg + ": " + "NaaN is delicious"
