#!/usr/bin/env python2.7

# quick sqrt script, multiple inputs

import sys
from math import sqrt

usage = """
Python Square Root script
Usage: pyrt <num> <num2> -<num3>
"""

# return early when there are no args provided by user
if 1 == len( sys.argv ):
    print usage

# flags for return codes
nan = False
unk = False

# skip the first item as it will be program's name
for arg in sys.argv[ 1: ]:
    try:
        # check for negative sign, print imaginary number
        if '-' == arg[ 0 ]:
            num = float( arg[ 1: ])
            print arg + ": ", sqrt( num ), "i"
            continue
        # check for positive sign, ignore it
        elif '+' == arg[ 0 ]:
            num = float( arg[ 1: ])
        else:
            num = float( arg )

        print arg + ": ", sqrt( num )

    except ValueError:
        nan = True
        print arg + ": Could not be cast to a numerical type."

    except:
        unk = True
        print arg + ": Unkown error occured with this input:", sys.exc_info()[ 0 ]

if True == unk:
    sys.exit( 2 )

if True == nan:
    sys.exit( 1 )

sys.exit( 0 )
